#pragma once

#define RIFT_VERSION_MAJOR 1
#define RIFT_VERSION_MINOR 1
#define RIFT_VERSION_PATCH 2

#define RIFT_STRINGIFY_IMPL(x) #x
#define RIFT_STRINGIFY(x) RIFT_STRINGIFY_IMPL(x)

#define RIFT_VERSION_STRING \
	RIFT_STRINGIFY(RIFT_VERSION_MAJOR) "." RIFT_STRINGIFY(RIFT_VERSION_MINOR) "." RIFT_STRINGIFY(RIFT_VERSION_PATCH)
